// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 1314990121;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__all_snapshot_wire_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "all_snapshot_wire_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::AllSnapshotWire::default())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__beatjump_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "beatjump",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_deck = <u32>::sse_decode(&mut deserializer);
            let api_beats = <f64>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::beatjump(api_deck, api_beats);
                })?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__bus_get_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "bus_get",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::bus_get(api_path))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__bus_set_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "bus_set",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_path = <String>::sse_decode(&mut deserializer);
            let api_value = <f64>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::bus_set(api_path, api_value);
                })?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__deck_snapshot_wire_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "deck_snapshot_wire_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::DeckSnapshotWire::default())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__fx_effect_wire_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "fx_effect_wire_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::FxEffectWire::default())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__fx_manifests_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "fx_manifests",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::fx_manifests())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__fx_param_wire_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "fx_param_wire_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::FxParamWire::default())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__init_engine_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_engine",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, String>((move || {
                let output_ok = crate::api::init_engine()?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__load_track_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "load_track",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_deck = <u32>::sse_decode(&mut deserializer);
            let api_path = <String>::sse_decode(&mut deserializer);
            let api_sink = <StreamSink<
                crate::api::AnalysisEventWire,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::load_track(api_deck, api_path, api_sink);
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__master_snapshot_wire_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "master_snapshot_wire_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::MasterSnapshotWire::default())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__pick_audio_file_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "pick_audio_file",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::pick_audio_file())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__ping_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ping",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::ping())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__read_metadata_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "read_metadata",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::read_metadata(api_path)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__seek_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "seek",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_deck = <u32>::sse_decode(&mut deserializer);
            let api_seconds = <f64>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::seek(api_deck, api_seconds);
                })?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__seek_exact_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "seek_exact",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_deck = <u32>::sse_decode(&mut deserializer);
            let api_seconds = <f64>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::seek_exact(api_deck, api_seconds);
                })?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__set_analysis_priority_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "set_analysis_priority",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_deck = <u32>::sse_decode(&mut deserializer);
            let api_priority = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::set_analysis_priority(api_deck, api_priority);
                })?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__set_beat_loop_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "set_beat_loop",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_deck = <u32>::sse_decode(&mut deserializer);
            let api_beats = <f64>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::set_beat_loop(api_deck, api_beats);
                })?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__snapshot_all_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "snapshot_all",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::snapshot_all())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__track_metadata_wire_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "track_metadata_wire_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::TrackMetadataWire::default())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__wire_column_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "wire_column_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::WireColumn::default())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<crate::api::AnalysisEventWire, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::AllSnapshotWire {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_deck0 = <crate::api::DeckSnapshotWire>::sse_decode(deserializer);
        let mut var_deck1 = <crate::api::DeckSnapshotWire>::sse_decode(deserializer);
        let mut var_master = <crate::api::MasterSnapshotWire>::sse_decode(deserializer);
        return crate::api::AllSnapshotWire {
            deck0: var_deck0,
            deck1: var_deck1,
            master: var_master,
        };
    }
}

impl SseDecode for crate::api::AnalysisEventWire {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_generation = <u64>::sse_decode(deserializer);
                let mut var_seg = <u32>::sse_decode(deserializer);
                let mut var_detail = <Vec<crate::api::WireColumn>>::sse_decode(deserializer);
                let mut var_overview = <Vec<crate::api::WireColumn>>::sse_decode(deserializer);
                return crate::api::AnalysisEventWire::Segment {
                    generation: var_generation,
                    seg: var_seg,
                    detail: var_detail,
                    overview: var_overview,
                };
            }
            1 => {
                let mut var_generation = <u64>::sse_decode(deserializer);
                let mut var_bpm = <f64>::sse_decode(deserializer);
                let mut var_keyName = <String>::sse_decode(deserializer);
                let mut var_keyCamelot = <String>::sse_decode(deserializer);
                let mut var_offsetSecs = <f64>::sse_decode(deserializer);
                let mut var_beatsSecs = <Vec<f64>>::sse_decode(deserializer);
                let mut var_downbeatsSecs = <Vec<f64>>::sse_decode(deserializer);
                let mut var_confidence = <f32>::sse_decode(deserializer);
                let mut var_tempoSegments = <Vec<(f64, f64, f32)>>::sse_decode(deserializer);
                return crate::api::AnalysisEventWire::TrackAnalysis {
                    generation: var_generation,
                    bpm: var_bpm,
                    key_name: var_keyName,
                    key_camelot: var_keyCamelot,
                    offset_secs: var_offsetSecs,
                    beats_secs: var_beatsSecs,
                    downbeats_secs: var_downbeatsSecs,
                    confidence: var_confidence,
                    tempo_segments: var_tempoSegments,
                };
            }
            2 => {
                let mut var_generation = <u64>::sse_decode(deserializer);
                let mut var_detail = <Vec<crate::api::WireColumn>>::sse_decode(deserializer);
                let mut var_overview = <Vec<crate::api::WireColumn>>::sse_decode(deserializer);
                let mut var_framesPerCol = <u32>::sse_decode(deserializer);
                let mut var_sampleRate = <u32>::sse_decode(deserializer);
                let mut var_durationFrames = <u64>::sse_decode(deserializer);
                return crate::api::AnalysisEventWire::Done {
                    generation: var_generation,
                    detail: var_detail,
                    overview: var_overview,
                    frames_per_col: var_framesPerCol,
                    sample_rate: var_sampleRate,
                    duration_frames: var_durationFrames,
                };
            }
            3 => {
                let mut var_generation = <u64>::sse_decode(deserializer);
                let mut var_msg = <String>::sse_decode(deserializer);
                return crate::api::AnalysisEventWire::Failed {
                    generation: var_generation,
                    msg: var_msg,
                };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::DeckSnapshotWire {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_playhead = <f64>::sse_decode(deserializer);
        let mut var_duration = <f64>::sse_decode(deserializer);
        let mut var_loaded = <f64>::sse_decode(deserializer);
        let mut var_playing = <f64>::sse_decode(deserializer);
        let mut var_vu = <f64>::sse_decode(deserializer);
        let mut var_rate = <f64>::sse_decode(deserializer);
        let mut var_volume = <f64>::sse_decode(deserializer);
        let mut var_bpm = <f64>::sse_decode(deserializer);
        let mut var_gridBpm = <f64>::sse_decode(deserializer);
        let mut var_keylock = <f64>::sse_decode(deserializer);
        let mut var_sync_ = <f64>::sse_decode(deserializer);
        let mut var_loopActive = <f64>::sse_decode(deserializer);
        let mut var_loopIn = <f64>::sse_decode(deserializer);
        let mut var_loopOut = <f64>::sse_decode(deserializer);
        let mut var_eqLow = <f64>::sse_decode(deserializer);
        let mut var_eqMid = <f64>::sse_decode(deserializer);
        let mut var_eqHigh = <f64>::sse_decode(deserializer);
        let mut var_cacheFilled = <f64>::sse_decode(deserializer);
        return crate::api::DeckSnapshotWire {
            playhead: var_playhead,
            duration: var_duration,
            loaded: var_loaded,
            playing: var_playing,
            vu: var_vu,
            rate: var_rate,
            volume: var_volume,
            bpm: var_bpm,
            grid_bpm: var_gridBpm,
            keylock: var_keylock,
            sync: var_sync_,
            loop_active: var_loopActive,
            loop_in: var_loopIn,
            loop_out: var_loopOut,
            eq_low: var_eqLow,
            eq_mid: var_eqMid,
            eq_high: var_eqHigh,
            cache_filled: var_cacheFilled,
        };
    }
}

impl SseDecode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::FxEffectWire {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <u32>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_label = <String>::sse_decode(deserializer);
        let mut var_params = <Vec<crate::api::FxParamWire>>::sse_decode(deserializer);
        return crate::api::FxEffectWire {
            id: var_id,
            name: var_name,
            label: var_label,
            params: var_params,
        };
    }
}

impl SseDecode for crate::api::FxParamWire {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_label = <String>::sse_decode(deserializer);
        let mut var_unit = <String>::sse_decode(deserializer);
        let mut var_kindStepped = <bool>::sse_decode(deserializer);
        let mut var_kindMin = <f64>::sse_decode(deserializer);
        let mut var_kindMax = <f64>::sse_decode(deserializer);
        let mut var_kindStep = <f64>::sse_decode(deserializer);
        let mut var_defaultValue = <f64>::sse_decode(deserializer);
        return crate::api::FxParamWire {
            name: var_name,
            label: var_label,
            unit: var_unit,
            kind_stepped: var_kindStepped,
            kind_min: var_kindMin,
            kind_max: var_kindMax,
            kind_step: var_kindStep,
            default_value: var_defaultValue,
        };
    }
}

impl SseDecode for Vec<crate::api::FxEffectWire> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::FxEffectWire>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::FxParamWire> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::FxParamWire>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<f64>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<(f64, f64, f32)> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<(f64, f64, f32)>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::WireColumn> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::WireColumn>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::MasterSnapshotWire {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_volume = <f64>::sse_decode(deserializer);
        let mut var_vu = <f64>::sse_decode(deserializer);
        return crate::api::MasterSnapshotWire {
            volume: var_volume,
            vu: var_vu,
        };
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for (f64, f64, f32) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_field0 = <f64>::sse_decode(deserializer);
        let mut var_field1 = <f64>::sse_decode(deserializer);
        let mut var_field2 = <f32>::sse_decode(deserializer);
        return (var_field0, var_field1, var_field2);
    }
}

impl SseDecode for crate::api::TrackMetadataWire {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_title = <Option<String>>::sse_decode(deserializer);
        let mut var_artist = <Option<String>>::sse_decode(deserializer);
        let mut var_cover = <Vec<u8>>::sse_decode(deserializer);
        let mut var_coverMime = <String>::sse_decode(deserializer);
        return crate::api::TrackMetadataWire {
            title: var_title,
            artist: var_artist,
            cover: var_cover,
            cover_mime: var_coverMime,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for crate::api::WireColumn {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_lowP = <u8>::sse_decode(deserializer);
        let mut var_lowN = <u8>::sse_decode(deserializer);
        let mut var_midP = <u8>::sse_decode(deserializer);
        let mut var_midN = <u8>::sse_decode(deserializer);
        let mut var_highP = <u8>::sse_decode(deserializer);
        let mut var_highN = <u8>::sse_decode(deserializer);
        let mut var_allP = <u8>::sse_decode(deserializer);
        let mut var_allN = <u8>::sse_decode(deserializer);
        return crate::api::WireColumn {
            low_p: var_lowP,
            low_n: var_lowN,
            mid_p: var_midP,
            mid_n: var_midN,
            high_p: var_highP,
            high_n: var_highN,
            all_p: var_allP,
            all_n: var_allN,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__all_snapshot_wire_default_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__crate__api__deck_snapshot_wire_default_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__fx_effect_wire_default_impl(port, ptr, rust_vec_len, data_len),
        8 => wire__crate__api__fx_param_wire_default_impl(port, ptr, rust_vec_len, data_len),
        10 => wire__crate__api__load_track_impl(port, ptr, rust_vec_len, data_len),
        11 => {
            wire__crate__api__master_snapshot_wire_default_impl(port, ptr, rust_vec_len, data_len)
        }
        14 => wire__crate__api__read_metadata_impl(port, ptr, rust_vec_len, data_len),
        20 => wire__crate__api__track_metadata_wire_default_impl(port, ptr, rust_vec_len, data_len),
        21 => wire__crate__api__wire_column_default_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        2 => wire__crate__api__beatjump_impl(ptr, rust_vec_len, data_len),
        3 => wire__crate__api__bus_get_impl(ptr, rust_vec_len, data_len),
        4 => wire__crate__api__bus_set_impl(ptr, rust_vec_len, data_len),
        7 => wire__crate__api__fx_manifests_impl(ptr, rust_vec_len, data_len),
        9 => wire__crate__api__init_engine_impl(ptr, rust_vec_len, data_len),
        12 => wire__crate__api__pick_audio_file_impl(ptr, rust_vec_len, data_len),
        13 => wire__crate__api__ping_impl(ptr, rust_vec_len, data_len),
        15 => wire__crate__api__seek_impl(ptr, rust_vec_len, data_len),
        16 => wire__crate__api__seek_exact_impl(ptr, rust_vec_len, data_len),
        17 => wire__crate__api__set_analysis_priority_impl(ptr, rust_vec_len, data_len),
        18 => wire__crate__api__set_beat_loop_impl(ptr, rust_vec_len, data_len),
        19 => wire__crate__api__snapshot_all_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::AllSnapshotWire {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.deck0.into_into_dart().into_dart(),
            self.deck1.into_into_dart().into_dart(),
            self.master.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::AllSnapshotWire {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::AllSnapshotWire>
    for crate::api::AllSnapshotWire
{
    fn into_into_dart(self) -> crate::api::AllSnapshotWire {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::AnalysisEventWire {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::AnalysisEventWire::Segment {
                generation,
                seg,
                detail,
                overview,
            } => [
                0.into_dart(),
                generation.into_into_dart().into_dart(),
                seg.into_into_dart().into_dart(),
                detail.into_into_dart().into_dart(),
                overview.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::AnalysisEventWire::TrackAnalysis {
                generation,
                bpm,
                key_name,
                key_camelot,
                offset_secs,
                beats_secs,
                downbeats_secs,
                confidence,
                tempo_segments,
            } => [
                1.into_dart(),
                generation.into_into_dart().into_dart(),
                bpm.into_into_dart().into_dart(),
                key_name.into_into_dart().into_dart(),
                key_camelot.into_into_dart().into_dart(),
                offset_secs.into_into_dart().into_dart(),
                beats_secs.into_into_dart().into_dart(),
                downbeats_secs.into_into_dart().into_dart(),
                confidence.into_into_dart().into_dart(),
                tempo_segments.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::AnalysisEventWire::Done {
                generation,
                detail,
                overview,
                frames_per_col,
                sample_rate,
                duration_frames,
            } => [
                2.into_dart(),
                generation.into_into_dart().into_dart(),
                detail.into_into_dart().into_dart(),
                overview.into_into_dart().into_dart(),
                frames_per_col.into_into_dart().into_dart(),
                sample_rate.into_into_dart().into_dart(),
                duration_frames.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::AnalysisEventWire::Failed { generation, msg } => [
                3.into_dart(),
                generation.into_into_dart().into_dart(),
                msg.into_into_dart().into_dart(),
            ]
            .into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::AnalysisEventWire {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::AnalysisEventWire>
    for crate::api::AnalysisEventWire
{
    fn into_into_dart(self) -> crate::api::AnalysisEventWire {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::DeckSnapshotWire {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.playhead.into_into_dart().into_dart(),
            self.duration.into_into_dart().into_dart(),
            self.loaded.into_into_dart().into_dart(),
            self.playing.into_into_dart().into_dart(),
            self.vu.into_into_dart().into_dart(),
            self.rate.into_into_dart().into_dart(),
            self.volume.into_into_dart().into_dart(),
            self.bpm.into_into_dart().into_dart(),
            self.grid_bpm.into_into_dart().into_dart(),
            self.keylock.into_into_dart().into_dart(),
            self.sync.into_into_dart().into_dart(),
            self.loop_active.into_into_dart().into_dart(),
            self.loop_in.into_into_dart().into_dart(),
            self.loop_out.into_into_dart().into_dart(),
            self.eq_low.into_into_dart().into_dart(),
            self.eq_mid.into_into_dart().into_dart(),
            self.eq_high.into_into_dart().into_dart(),
            self.cache_filled.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::DeckSnapshotWire {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::DeckSnapshotWire>
    for crate::api::DeckSnapshotWire
{
    fn into_into_dart(self) -> crate::api::DeckSnapshotWire {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FxEffectWire {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.label.into_into_dart().into_dart(),
            self.params.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::FxEffectWire {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FxEffectWire> for crate::api::FxEffectWire {
    fn into_into_dart(self) -> crate::api::FxEffectWire {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::FxParamWire {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.label.into_into_dart().into_dart(),
            self.unit.into_into_dart().into_dart(),
            self.kind_stepped.into_into_dart().into_dart(),
            self.kind_min.into_into_dart().into_dart(),
            self.kind_max.into_into_dart().into_dart(),
            self.kind_step.into_into_dart().into_dart(),
            self.default_value.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::FxParamWire {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::FxParamWire> for crate::api::FxParamWire {
    fn into_into_dart(self) -> crate::api::FxParamWire {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::MasterSnapshotWire {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.volume.into_into_dart().into_dart(),
            self.vu.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::MasterSnapshotWire
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::MasterSnapshotWire>
    for crate::api::MasterSnapshotWire
{
    fn into_into_dart(self) -> crate::api::MasterSnapshotWire {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::TrackMetadataWire {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.title.into_into_dart().into_dart(),
            self.artist.into_into_dart().into_dart(),
            self.cover.into_into_dart().into_dart(),
            self.cover_mime.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::TrackMetadataWire {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::TrackMetadataWire>
    for crate::api::TrackMetadataWire
{
    fn into_into_dart(self) -> crate::api::TrackMetadataWire {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::WireColumn {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.low_p.into_into_dart().into_dart(),
            self.low_n.into_into_dart().into_dart(),
            self.mid_p.into_into_dart().into_dart(),
            self.mid_n.into_into_dart().into_dart(),
            self.high_p.into_into_dart().into_dart(),
            self.high_n.into_into_dart().into_dart(),
            self.all_p.into_into_dart().into_dart(),
            self.all_n.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::WireColumn {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::WireColumn> for crate::api::WireColumn {
    fn into_into_dart(self) -> crate::api::WireColumn {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<crate::api::AnalysisEventWire, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::AllSnapshotWire {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::DeckSnapshotWire>::sse_encode(self.deck0, serializer);
        <crate::api::DeckSnapshotWire>::sse_encode(self.deck1, serializer);
        <crate::api::MasterSnapshotWire>::sse_encode(self.master, serializer);
    }
}

impl SseEncode for crate::api::AnalysisEventWire {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::AnalysisEventWire::Segment {
                generation,
                seg,
                detail,
                overview,
            } => {
                <i32>::sse_encode(0, serializer);
                <u64>::sse_encode(generation, serializer);
                <u32>::sse_encode(seg, serializer);
                <Vec<crate::api::WireColumn>>::sse_encode(detail, serializer);
                <Vec<crate::api::WireColumn>>::sse_encode(overview, serializer);
            }
            crate::api::AnalysisEventWire::TrackAnalysis {
                generation,
                bpm,
                key_name,
                key_camelot,
                offset_secs,
                beats_secs,
                downbeats_secs,
                confidence,
                tempo_segments,
            } => {
                <i32>::sse_encode(1, serializer);
                <u64>::sse_encode(generation, serializer);
                <f64>::sse_encode(bpm, serializer);
                <String>::sse_encode(key_name, serializer);
                <String>::sse_encode(key_camelot, serializer);
                <f64>::sse_encode(offset_secs, serializer);
                <Vec<f64>>::sse_encode(beats_secs, serializer);
                <Vec<f64>>::sse_encode(downbeats_secs, serializer);
                <f32>::sse_encode(confidence, serializer);
                <Vec<(f64, f64, f32)>>::sse_encode(tempo_segments, serializer);
            }
            crate::api::AnalysisEventWire::Done {
                generation,
                detail,
                overview,
                frames_per_col,
                sample_rate,
                duration_frames,
            } => {
                <i32>::sse_encode(2, serializer);
                <u64>::sse_encode(generation, serializer);
                <Vec<crate::api::WireColumn>>::sse_encode(detail, serializer);
                <Vec<crate::api::WireColumn>>::sse_encode(overview, serializer);
                <u32>::sse_encode(frames_per_col, serializer);
                <u32>::sse_encode(sample_rate, serializer);
                <u64>::sse_encode(duration_frames, serializer);
            }
            crate::api::AnalysisEventWire::Failed { generation, msg } => {
                <i32>::sse_encode(3, serializer);
                <u64>::sse_encode(generation, serializer);
                <String>::sse_encode(msg, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::DeckSnapshotWire {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f64>::sse_encode(self.playhead, serializer);
        <f64>::sse_encode(self.duration, serializer);
        <f64>::sse_encode(self.loaded, serializer);
        <f64>::sse_encode(self.playing, serializer);
        <f64>::sse_encode(self.vu, serializer);
        <f64>::sse_encode(self.rate, serializer);
        <f64>::sse_encode(self.volume, serializer);
        <f64>::sse_encode(self.bpm, serializer);
        <f64>::sse_encode(self.grid_bpm, serializer);
        <f64>::sse_encode(self.keylock, serializer);
        <f64>::sse_encode(self.sync, serializer);
        <f64>::sse_encode(self.loop_active, serializer);
        <f64>::sse_encode(self.loop_in, serializer);
        <f64>::sse_encode(self.loop_out, serializer);
        <f64>::sse_encode(self.eq_low, serializer);
        <f64>::sse_encode(self.eq_mid, serializer);
        <f64>::sse_encode(self.eq_high, serializer);
        <f64>::sse_encode(self.cache_filled, serializer);
    }
}

impl SseEncode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::FxEffectWire {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.label, serializer);
        <Vec<crate::api::FxParamWire>>::sse_encode(self.params, serializer);
    }
}

impl SseEncode for crate::api::FxParamWire {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <String>::sse_encode(self.label, serializer);
        <String>::sse_encode(self.unit, serializer);
        <bool>::sse_encode(self.kind_stepped, serializer);
        <f64>::sse_encode(self.kind_min, serializer);
        <f64>::sse_encode(self.kind_max, serializer);
        <f64>::sse_encode(self.kind_step, serializer);
        <f64>::sse_encode(self.default_value, serializer);
    }
}

impl SseEncode for Vec<crate::api::FxEffectWire> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::FxEffectWire>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::FxParamWire> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::FxParamWire>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <f64>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<(f64, f64, f32)> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <(f64, f64, f32)>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::WireColumn> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::WireColumn>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::MasterSnapshotWire {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f64>::sse_encode(self.volume, serializer);
        <f64>::sse_encode(self.vu, serializer);
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for (f64, f64, f32) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f64>::sse_encode(self.0, serializer);
        <f64>::sse_encode(self.1, serializer);
        <f32>::sse_encode(self.2, serializer);
    }
}

impl SseEncode for crate::api::TrackMetadataWire {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<String>>::sse_encode(self.title, serializer);
        <Option<String>>::sse_encode(self.artist, serializer);
        <Vec<u8>>::sse_encode(self.cover, serializer);
        <String>::sse_encode(self.cover_mime, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::api::WireColumn {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u8>::sse_encode(self.low_p, serializer);
        <u8>::sse_encode(self.low_n, serializer);
        <u8>::sse_encode(self.mid_p, serializer);
        <u8>::sse_encode(self.mid_n, serializer);
        <u8>::sse_encode(self.high_p, serializer);
        <u8>::sse_encode(self.high_n, serializer);
        <u8>::sse_encode(self.all_p, serializer);
        <u8>::sse_encode(self.all_n, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
