// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// 冒烟回路：桥库已加载的证明。
BigInt ping() => RustLib.instance.api.crateApiPing();

/// 启动引擎（CpalBackend::new + Engine::start）。幂等。
/// 失败（无音频设备等）返回错误串，Flutter 顶部红条显示；之后才可载曲/取快照。
void initEngine() => RustLib.instance.api.crateApiInitEngine();

/// 载曲到 deck 并启动渐进分析，事件推入 `sink`
/// （Segment → TrackAnalysis → Done/Failed，每条带 generation）。
/// 重复调用 = 重载：旧分析线程停掉、旧事件按代际作废。
/// 引擎语义：载入即自动开播。
Stream<AnalysisEventWire> loadTrack({
  required int deck,
  required String path,
}) => RustLib.instance.api.crateApiLoadTrack(deck: deck, path: path);

/// 跳到指定秒。
void seek({required int deck, required double seconds}) =>
    RustLib.instance.api.crateApiSeek(deck: deck, seconds: seconds);

/// 精确跳转（不量化；cue/hotcue 召回用）。
void seekExact({required int deck, required double seconds}) =>
    RustLib.instance.api.crateApiSeekExact(deck: deck, seconds: seconds);

/// 按拍跳跃（简单加减，拍长匹配当前速度）。
void beatjump({required int deck, required double beats}) =>
    RustLib.instance.api.crateApiBeatjump(deck: deck, beats: beats);

/// 激活/调整 beat loop（量化起止；取消由 UI 写 loop_active=0）。
void setBeatLoop({required int deck, required double beats}) =>
    RustLib.instance.api.crateApiSetBeatLoop(deck: deck, beats: beats);

/// 写控制总线（音量 / rate / sync / keylock / zoom 等任意 paths）。
void busSet({required String path, required double value}) =>
    RustLib.instance.api.crateApiBusSet(path: path, value: value);

double busGet({required String path}) =>
    RustLib.instance.api.crateApiBusGet(path: path);

/// 60Hz 全量快照：全 f64、零字符串、零分配，Dart 侧单次同步调用。
/// 桥未初始化时返回全零结构。
AllSnapshotWire snapshotAll() => RustLib.instance.api.crateApiSnapshotAll();

/// FX 效果静态清单（manifest 是 Flutter 生成 FX 面板参数的唯一入口）。
/// 启动时调用一次并缓存；效果/参数顺序与 EffectId 判别值一致。
List<FxEffectWire> fxManifests() => RustLib.instance.api.crateApiFxManifests();

/// 播放头所在分析段（UI 每 tick 更新，分析线程按距其远近排序）。
void setAnalysisPriority({required int deck, required int priority}) => RustLib
    .instance
    .api
    .crateApiSetAnalysisPriority(deck: deck, priority: priority);

/// 读曲目元数据（title/artist/封面，lofty）。几十 ms，载曲动作用。
Future<TrackMetadataWire> readMetadata({required String path}) =>
    RustLib.instance.api.crateApiReadMetadata(path: path);

/// 打开系统文件选择对话框（rfd/XDG portal，复刻 Slint 加载按钮）。
/// 阻塞 UI 线程直到选择/取消；取消返回 None。
String? pickAudioFile() => RustLib.instance.api.crateApiPickAudioFile();

class AllSnapshotWire {
  final DeckSnapshotWire deck0;
  final DeckSnapshotWire deck1;
  final MasterSnapshotWire master;

  const AllSnapshotWire({
    required this.deck0,
    required this.deck1,
    required this.master,
  });

  static Future<AllSnapshotWire> default_() =>
      RustLib.instance.api.crateApiAllSnapshotWireDefault();

  @override
  int get hashCode => deck0.hashCode ^ deck1.hashCode ^ master.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AllSnapshotWire &&
          runtimeType == other.runtimeType &&
          deck0 == other.deck0 &&
          deck1 == other.deck1 &&
          master == other.master;
}

@freezed
sealed class AnalysisEventWire with _$AnalysisEventWire {
  const AnalysisEventWire._();

  /// 一段分析完成（满刻度 √ 压缩显示值；全曲完成后由 Done 替换）。
  const factory AnalysisEventWire.segment({
    required BigInt generation,
    required int seg,
    required List<WireColumn> detail,
    required List<WireColumn> overview,
  }) = AnalysisEventWire_Segment;

  /// 单遍 BPM/调性/beatgrid 结果，Done 之前发出。bpm=0 = 未检测到。
  const factory AnalysisEventWire.trackAnalysis({
    required BigInt generation,
    required double bpm,
    required String keyName,
    required String keyCamelot,

    /// 首拍秒偏移（grid 为空时为 0）。
    required double offsetSecs,
    required Float64List beatsSecs,
    required Float64List downbeatsSecs,
    required double confidence,
  }) = AnalysisEventWire_TrackAnalysis;

  /// 全曲分析完成：全局归一化数据（渐进分段由它整体替换）。
  const factory AnalysisEventWire.done({
    required BigInt generation,
    required List<WireColumn> detail,
    required List<WireColumn> overview,
    required int framesPerCol,
    required int sampleRate,
    required BigInt durationFrames,
  }) = AnalysisEventWire_Done;
  const factory AnalysisEventWire.failed({
    required BigInt generation,
    required String msg,
  }) = AnalysisEventWire_Failed;
}

/// 单 deck 快照（60Hz）。字段与总线 paths 一一对应。
class DeckSnapshotWire {
  final double playhead;
  final double duration;
  final double loaded;
  final double playing;
  final double vu;
  final double rate;
  final double volume;
  final double bpm;
  final double gridBpm;
  final double keylock;
  final double sync_;

  /// beat loop 状态（active 0/1；in/out 秒，未激活时为 0）。
  final double loopActive;
  final double loopIn;
  final double loopOut;

  /// EQ 三带增益（dB，-40..+6，0 = 直通）。
  final double eqLow;
  final double eqMid;
  final double eqHigh;

  const DeckSnapshotWire({
    required this.playhead,
    required this.duration,
    required this.loaded,
    required this.playing,
    required this.vu,
    required this.rate,
    required this.volume,
    required this.bpm,
    required this.gridBpm,
    required this.keylock,
    required this.sync_,
    required this.loopActive,
    required this.loopIn,
    required this.loopOut,
    required this.eqLow,
    required this.eqMid,
    required this.eqHigh,
  });

  static Future<DeckSnapshotWire> default_() =>
      RustLib.instance.api.crateApiDeckSnapshotWireDefault();

  @override
  int get hashCode =>
      playhead.hashCode ^
      duration.hashCode ^
      loaded.hashCode ^
      playing.hashCode ^
      vu.hashCode ^
      rate.hashCode ^
      volume.hashCode ^
      bpm.hashCode ^
      gridBpm.hashCode ^
      keylock.hashCode ^
      sync_.hashCode ^
      loopActive.hashCode ^
      loopIn.hashCode ^
      loopOut.hashCode ^
      eqLow.hashCode ^
      eqMid.hashCode ^
      eqHigh.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeckSnapshotWire &&
          runtimeType == other.runtimeType &&
          playhead == other.playhead &&
          duration == other.duration &&
          loaded == other.loaded &&
          playing == other.playing &&
          vu == other.vu &&
          rate == other.rate &&
          volume == other.volume &&
          bpm == other.bpm &&
          gridBpm == other.gridBpm &&
          keylock == other.keylock &&
          sync_ == other.sync_ &&
          loopActive == other.loopActive &&
          loopIn == other.loopIn &&
          loopOut == other.loopOut &&
          eqLow == other.eqLow &&
          eqMid == other.eqMid &&
          eqHigh == other.eqHigh;
}

/// 单效果清单（id = EffectId 判别值 1..=8；params 位对应总线 fxN_p1..p4）。
class FxEffectWire {
  final int id;
  final String name;
  final String label;
  final List<FxParamWire> params;

  const FxEffectWire({
    required this.id,
    required this.name,
    required this.label,
    required this.params,
  });

  static Future<FxEffectWire> default_() =>
      RustLib.instance.api.crateApiFxEffectWireDefault();

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ label.hashCode ^ params.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FxEffectWire &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          label == other.label &&
          params == other.params;
}

/// FX 单参数规格（manifest 参数，自然单位）。
/// `kind_stepped=false` → 连续滑杆；`true` → 离散步进（Slider divisions）。
/// 字段名避开 Dart 关键字 `default`（FRB 会把 `default` 生成冲突的 static 方法）。
class FxParamWire {
  final String name;
  final String label;
  final String unit;
  final bool kindStepped;
  final double kindMin;
  final double kindMax;
  final double kindStep;
  final double defaultValue;

  const FxParamWire({
    required this.name,
    required this.label,
    required this.unit,
    required this.kindStepped,
    required this.kindMin,
    required this.kindMax,
    required this.kindStep,
    required this.defaultValue,
  });

  static Future<FxParamWire> default_() =>
      RustLib.instance.api.crateApiFxParamWireDefault();

  @override
  int get hashCode =>
      name.hashCode ^
      label.hashCode ^
      unit.hashCode ^
      kindStepped.hashCode ^
      kindMin.hashCode ^
      kindMax.hashCode ^
      kindStep.hashCode ^
      defaultValue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FxParamWire &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          label == other.label &&
          unit == other.unit &&
          kindStepped == other.kindStepped &&
          kindMin == other.kindMin &&
          kindMax == other.kindMax &&
          kindStep == other.kindStep &&
          defaultValue == other.defaultValue;
}

class MasterSnapshotWire {
  final double volume;
  final double vu;

  const MasterSnapshotWire({required this.volume, required this.vu});

  static Future<MasterSnapshotWire> default_() =>
      RustLib.instance.api.crateApiMasterSnapshotWireDefault();

  @override
  int get hashCode => volume.hashCode ^ vu.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MasterSnapshotWire &&
          runtimeType == other.runtimeType &&
          volume == other.volume &&
          vu == other.vu;
}

/// 曲目元数据。封面原始字节（FLAC 内嵌图由 lofty 解出）。
class TrackMetadataWire {
  final String? title;
  final String? artist;
  final Uint8List cover;

  /// 如 `image/jpeg`；无封面时为空串。
  final String coverMime;

  const TrackMetadataWire({
    this.title,
    this.artist,
    required this.cover,
    required this.coverMime,
  });

  static Future<TrackMetadataWire> default_() =>
      RustLib.instance.api.crateApiTrackMetadataWireDefault();

  @override
  int get hashCode =>
      title.hashCode ^ artist.hashCode ^ cover.hashCode ^ coverMime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackMetadataWire &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artist == other.artist &&
          cover == other.cover &&
          coverMime == other.coverMime;
}

/// 波形单列 8 值：`*_p` = 正峰、`*_n` = 负半折叠幅度（|min|），全部 ≥0。
/// 半波预览 = p 全 α 矩形 + n α0.55 矩形（折叠整流）；对称波形 = max(p, n)。
class WireColumn {
  final int lowP;
  final int lowN;
  final int midP;
  final int midN;
  final int highP;
  final int highN;
  final int allP;
  final int allN;

  const WireColumn({
    required this.lowP,
    required this.lowN,
    required this.midP,
    required this.midN,
    required this.highP,
    required this.highN,
    required this.allP,
    required this.allN,
  });

  static Future<WireColumn> default_() =>
      RustLib.instance.api.crateApiWireColumnDefault();

  @override
  int get hashCode =>
      lowP.hashCode ^
      lowN.hashCode ^
      midP.hashCode ^
      midN.hashCode ^
      highP.hashCode ^
      highN.hashCode ^
      allP.hashCode ^
      allN.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WireColumn &&
          runtimeType == other.runtimeType &&
          lowP == other.lowP &&
          lowN == other.lowN &&
          midP == other.midP &&
          midN == other.midN &&
          highP == other.highP &&
          highN == other.highN &&
          allP == other.allP &&
          allN == other.allN;
}
