// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<AnalysisEventWire>
  dco_decode_StreamSink_analysis_event_wire_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AllSnapshotWire dco_decode_all_snapshot_wire(dynamic raw);

  @protected
  AnalysisEventWire dco_decode_analysis_event_wire(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DeckSnapshotWire dco_decode_deck_snapshot_wire(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FxEffectWire dco_decode_fx_effect_wire(dynamic raw);

  @protected
  FxParamWire dco_decode_fx_param_wire(dynamic raw);

  @protected
  List<FxEffectWire> dco_decode_list_fx_effect_wire(dynamic raw);

  @protected
  List<FxParamWire> dco_decode_list_fx_param_wire(dynamic raw);

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(double, double, double)> dco_decode_list_record_f_64_f_64_f_32(
    dynamic raw,
  );

  @protected
  List<WireColumn> dco_decode_list_wire_column(dynamic raw);

  @protected
  MasterSnapshotWire dco_decode_master_snapshot_wire(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  (double, double, double) dco_decode_record_f_64_f_64_f_32(dynamic raw);

  @protected
  TrackMetadataWire dco_decode_track_metadata_wire(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WireColumn dco_decode_wire_column(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<AnalysisEventWire>
  sse_decode_StreamSink_analysis_event_wire_Sse(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AllSnapshotWire sse_decode_all_snapshot_wire(SseDeserializer deserializer);

  @protected
  AnalysisEventWire sse_decode_analysis_event_wire(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DeckSnapshotWire sse_decode_deck_snapshot_wire(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FxEffectWire sse_decode_fx_effect_wire(SseDeserializer deserializer);

  @protected
  FxParamWire sse_decode_fx_param_wire(SseDeserializer deserializer);

  @protected
  List<FxEffectWire> sse_decode_list_fx_effect_wire(
    SseDeserializer deserializer,
  );

  @protected
  List<FxParamWire> sse_decode_list_fx_param_wire(SseDeserializer deserializer);

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(double, double, double)> sse_decode_list_record_f_64_f_64_f_32(
    SseDeserializer deserializer,
  );

  @protected
  List<WireColumn> sse_decode_list_wire_column(SseDeserializer deserializer);

  @protected
  MasterSnapshotWire sse_decode_master_snapshot_wire(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  (double, double, double) sse_decode_record_f_64_f_64_f_32(
    SseDeserializer deserializer,
  );

  @protected
  TrackMetadataWire sse_decode_track_metadata_wire(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WireColumn sse_decode_wire_column(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_analysis_event_wire_Sse(
    RustStreamSink<AnalysisEventWire> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_all_snapshot_wire(
    AllSnapshotWire self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_analysis_event_wire(
    AnalysisEventWire self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_deck_snapshot_wire(
    DeckSnapshotWire self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_fx_effect_wire(FxEffectWire self, SseSerializer serializer);

  @protected
  void sse_encode_fx_param_wire(FxParamWire self, SseSerializer serializer);

  @protected
  void sse_encode_list_fx_effect_wire(
    List<FxEffectWire> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_fx_param_wire(
    List<FxParamWire> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_64_strict(
    Float64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_f_64_f_64_f_32(
    List<(double, double, double)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_wire_column(
    List<WireColumn> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_master_snapshot_wire(
    MasterSnapshotWire self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_record_f_64_f_64_f_32(
    (double, double, double) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_track_metadata_wire(
    TrackMetadataWire self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_wire_column(WireColumn self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
