// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1314990121;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'hypermixx_bridge',
        ioDirectory: '../HyperMixx/crates/hypermixx-bridge/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<AllSnapshotWire> crateApiAllSnapshotWireDefault();

  void crateApiBeatjump({required int deck, required double beats});

  double crateApiBusGet({required String path});

  void crateApiBusSet({required String path, required double value});

  Future<DeckSnapshotWire> crateApiDeckSnapshotWireDefault();

  Future<FxEffectWire> crateApiFxEffectWireDefault();

  List<FxEffectWire> crateApiFxManifests();

  Future<FxParamWire> crateApiFxParamWireDefault();

  void crateApiInitEngine();

  Stream<AnalysisEventWire> crateApiLoadTrack({
    required int deck,
    required String path,
  });

  Future<MasterSnapshotWire> crateApiMasterSnapshotWireDefault();

  String? crateApiPickAudioFile();

  BigInt crateApiPing();

  Future<TrackMetadataWire> crateApiReadMetadata({required String path});

  void crateApiSeek({required int deck, required double seconds});

  void crateApiSeekExact({required int deck, required double seconds});

  void crateApiSetAnalysisPriority({required int deck, required int priority});

  void crateApiSetBeatLoop({required int deck, required double beats});

  AllSnapshotWire crateApiSnapshotAll();

  Future<TrackMetadataWire> crateApiTrackMetadataWireDefault();

  Future<WireColumn> crateApiWireColumnDefault();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<AllSnapshotWire> crateApiAllSnapshotWireDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_all_snapshot_wire,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAllSnapshotWireDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAllSnapshotWireDefaultConstMeta =>
      const TaskConstMeta(debugName: "all_snapshot_wire_default", argNames: []);

  @override
  void crateApiBeatjump({required int deck, required double beats}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(deck, serializer);
          sse_encode_f_64(beats, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBeatjumpConstMeta,
        argValues: [deck, beats],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBeatjumpConstMeta =>
      const TaskConstMeta(debugName: "beatjump", argNames: ["deck", "beats"]);

  @override
  double crateApiBusGet({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBusGetConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBusGetConstMeta =>
      const TaskConstMeta(debugName: "bus_get", argNames: ["path"]);

  @override
  void crateApiBusSet({required String path, required double value}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_f_64(value, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBusSetConstMeta,
        argValues: [path, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBusSetConstMeta =>
      const TaskConstMeta(debugName: "bus_set", argNames: ["path", "value"]);

  @override
  Future<DeckSnapshotWire> crateApiDeckSnapshotWireDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_deck_snapshot_wire,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDeckSnapshotWireDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeckSnapshotWireDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "deck_snapshot_wire_default",
        argNames: [],
      );

  @override
  Future<FxEffectWire> crateApiFxEffectWireDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_fx_effect_wire,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFxEffectWireDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFxEffectWireDefaultConstMeta =>
      const TaskConstMeta(debugName: "fx_effect_wire_default", argNames: []);

  @override
  List<FxEffectWire> crateApiFxManifests() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_fx_effect_wire,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFxManifestsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFxManifestsConstMeta =>
      const TaskConstMeta(debugName: "fx_manifests", argNames: []);

  @override
  Future<FxParamWire> crateApiFxParamWireDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_fx_param_wire,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFxParamWireDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFxParamWireDefaultConstMeta =>
      const TaskConstMeta(debugName: "fx_param_wire_default", argNames: []);

  @override
  void crateApiInitEngine() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiInitEngineConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitEngineConstMeta =>
      const TaskConstMeta(debugName: "init_engine", argNames: []);

  @override
  Stream<AnalysisEventWire> crateApiLoadTrack({
    required int deck,
    required String path,
  }) {
    final sink = RustStreamSink<AnalysisEventWire>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_u_32(deck, serializer);
            sse_encode_String(path, serializer);
            sse_encode_StreamSink_analysis_event_wire_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 10,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiLoadTrackConstMeta,
          argValues: [deck, path, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiLoadTrackConstMeta => const TaskConstMeta(
    debugName: "load_track",
    argNames: ["deck", "path", "sink"],
  );

  @override
  Future<MasterSnapshotWire> crateApiMasterSnapshotWireDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_master_snapshot_wire,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMasterSnapshotWireDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMasterSnapshotWireDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "master_snapshot_wire_default",
        argNames: [],
      );

  @override
  String? crateApiPickAudioFile() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPickAudioFileConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPickAudioFileConstMeta =>
      const TaskConstMeta(debugName: "pick_audio_file", argNames: []);

  @override
  BigInt crateApiPing() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPingConstMeta =>
      const TaskConstMeta(debugName: "ping", argNames: []);

  @override
  Future<TrackMetadataWire> crateApiReadMetadata({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_track_metadata_wire,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiReadMetadataConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReadMetadataConstMeta =>
      const TaskConstMeta(debugName: "read_metadata", argNames: ["path"]);

  @override
  void crateApiSeek({required int deck, required double seconds}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(deck, serializer);
          sse_encode_f_64(seconds, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSeekConstMeta,
        argValues: [deck, seconds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSeekConstMeta =>
      const TaskConstMeta(debugName: "seek", argNames: ["deck", "seconds"]);

  @override
  void crateApiSeekExact({required int deck, required double seconds}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(deck, serializer);
          sse_encode_f_64(seconds, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSeekExactConstMeta,
        argValues: [deck, seconds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSeekExactConstMeta => const TaskConstMeta(
    debugName: "seek_exact",
    argNames: ["deck", "seconds"],
  );

  @override
  void crateApiSetAnalysisPriority({required int deck, required int priority}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(deck, serializer);
          sse_encode_u_32(priority, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSetAnalysisPriorityConstMeta,
        argValues: [deck, priority],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetAnalysisPriorityConstMeta =>
      const TaskConstMeta(
        debugName: "set_analysis_priority",
        argNames: ["deck", "priority"],
      );

  @override
  void crateApiSetBeatLoop({required int deck, required double beats}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(deck, serializer);
          sse_encode_f_64(beats, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSetBeatLoopConstMeta,
        argValues: [deck, beats],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetBeatLoopConstMeta => const TaskConstMeta(
    debugName: "set_beat_loop",
    argNames: ["deck", "beats"],
  );

  @override
  AllSnapshotWire crateApiSnapshotAll() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_all_snapshot_wire,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSnapshotAllConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSnapshotAllConstMeta =>
      const TaskConstMeta(debugName: "snapshot_all", argNames: []);

  @override
  Future<TrackMetadataWire> crateApiTrackMetadataWireDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_track_metadata_wire,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTrackMetadataWireDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTrackMetadataWireDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "track_metadata_wire_default",
        argNames: [],
      );

  @override
  Future<WireColumn> crateApiWireColumnDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_wire_column,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWireColumnDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWireColumnDefaultConstMeta =>
      const TaskConstMeta(debugName: "wire_column_default", argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<AnalysisEventWire>
  dco_decode_StreamSink_analysis_event_wire_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AllSnapshotWire dco_decode_all_snapshot_wire(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return AllSnapshotWire(
      deck0: dco_decode_deck_snapshot_wire(arr[0]),
      deck1: dco_decode_deck_snapshot_wire(arr[1]),
      master: dco_decode_master_snapshot_wire(arr[2]),
    );
  }

  @protected
  AnalysisEventWire dco_decode_analysis_event_wire(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return AnalysisEventWire_Segment(
          generation: dco_decode_u_64(raw[1]),
          seg: dco_decode_u_32(raw[2]),
          detail: dco_decode_list_wire_column(raw[3]),
          overview: dco_decode_list_wire_column(raw[4]),
        );
      case 1:
        return AnalysisEventWire_TrackAnalysis(
          generation: dco_decode_u_64(raw[1]),
          bpm: dco_decode_f_64(raw[2]),
          keyName: dco_decode_String(raw[3]),
          keyCamelot: dco_decode_String(raw[4]),
          offsetSecs: dco_decode_f_64(raw[5]),
          beatsSecs: dco_decode_list_prim_f_64_strict(raw[6]),
          downbeatsSecs: dco_decode_list_prim_f_64_strict(raw[7]),
          confidence: dco_decode_f_32(raw[8]),
          tempoSegments: dco_decode_list_record_f_64_f_64_f_32(raw[9]),
        );
      case 2:
        return AnalysisEventWire_Done(
          generation: dco_decode_u_64(raw[1]),
          detail: dco_decode_list_wire_column(raw[2]),
          overview: dco_decode_list_wire_column(raw[3]),
          framesPerCol: dco_decode_u_32(raw[4]),
          sampleRate: dco_decode_u_32(raw[5]),
          durationFrames: dco_decode_u_64(raw[6]),
        );
      case 3:
        return AnalysisEventWire_Failed(
          generation: dco_decode_u_64(raw[1]),
          msg: dco_decode_String(raw[2]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DeckSnapshotWire dco_decode_deck_snapshot_wire(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 18)
      throw Exception('unexpected arr length: expect 18 but see ${arr.length}');
    return DeckSnapshotWire(
      playhead: dco_decode_f_64(arr[0]),
      duration: dco_decode_f_64(arr[1]),
      loaded: dco_decode_f_64(arr[2]),
      playing: dco_decode_f_64(arr[3]),
      vu: dco_decode_f_64(arr[4]),
      rate: dco_decode_f_64(arr[5]),
      volume: dco_decode_f_64(arr[6]),
      bpm: dco_decode_f_64(arr[7]),
      gridBpm: dco_decode_f_64(arr[8]),
      keylock: dco_decode_f_64(arr[9]),
      sync_: dco_decode_f_64(arr[10]),
      loopActive: dco_decode_f_64(arr[11]),
      loopIn: dco_decode_f_64(arr[12]),
      loopOut: dco_decode_f_64(arr[13]),
      eqLow: dco_decode_f_64(arr[14]),
      eqMid: dco_decode_f_64(arr[15]),
      eqHigh: dco_decode_f_64(arr[16]),
      cacheFilled: dco_decode_f_64(arr[17]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FxEffectWire dco_decode_fx_effect_wire(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FxEffectWire(
      id: dco_decode_u_32(arr[0]),
      name: dco_decode_String(arr[1]),
      label: dco_decode_String(arr[2]),
      params: dco_decode_list_fx_param_wire(arr[3]),
    );
  }

  @protected
  FxParamWire dco_decode_fx_param_wire(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return FxParamWire(
      name: dco_decode_String(arr[0]),
      label: dco_decode_String(arr[1]),
      unit: dco_decode_String(arr[2]),
      kindStepped: dco_decode_bool(arr[3]),
      kindMin: dco_decode_f_64(arr[4]),
      kindMax: dco_decode_f_64(arr[5]),
      kindStep: dco_decode_f_64(arr[6]),
      defaultValue: dco_decode_f_64(arr[7]),
    );
  }

  @protected
  List<FxEffectWire> dco_decode_list_fx_effect_wire(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_fx_effect_wire).toList();
  }

  @protected
  List<FxParamWire> dco_decode_list_fx_param_wire(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_fx_param_wire).toList();
  }

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float64List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(double, double, double)> dco_decode_list_record_f_64_f_64_f_32(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_record_f_64_f_64_f_32)
        .toList();
  }

  @protected
  List<WireColumn> dco_decode_list_wire_column(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_wire_column).toList();
  }

  @protected
  MasterSnapshotWire dco_decode_master_snapshot_wire(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MasterSnapshotWire(
      volume: dco_decode_f_64(arr[0]),
      vu: dco_decode_f_64(arr[1]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  (double, double, double) dco_decode_record_f_64_f_64_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3) {
      throw Exception('Expected 3 elements, got ${arr.length}');
    }
    return (
      dco_decode_f_64(arr[0]),
      dco_decode_f_64(arr[1]),
      dco_decode_f_32(arr[2]),
    );
  }

  @protected
  TrackMetadataWire dco_decode_track_metadata_wire(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TrackMetadataWire(
      title: dco_decode_opt_String(arr[0]),
      artist: dco_decode_opt_String(arr[1]),
      cover: dco_decode_list_prim_u_8_strict(arr[2]),
      coverMime: dco_decode_String(arr[3]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WireColumn dco_decode_wire_column(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return WireColumn(
      lowP: dco_decode_u_8(arr[0]),
      lowN: dco_decode_u_8(arr[1]),
      midP: dco_decode_u_8(arr[2]),
      midN: dco_decode_u_8(arr[3]),
      highP: dco_decode_u_8(arr[4]),
      highN: dco_decode_u_8(arr[5]),
      allP: dco_decode_u_8(arr[6]),
      allN: dco_decode_u_8(arr[7]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<AnalysisEventWire>
  sse_decode_StreamSink_analysis_event_wire_Sse(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AllSnapshotWire sse_decode_all_snapshot_wire(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deck0 = sse_decode_deck_snapshot_wire(deserializer);
    var var_deck1 = sse_decode_deck_snapshot_wire(deserializer);
    var var_master = sse_decode_master_snapshot_wire(deserializer);
    return AllSnapshotWire(
      deck0: var_deck0,
      deck1: var_deck1,
      master: var_master,
    );
  }

  @protected
  AnalysisEventWire sse_decode_analysis_event_wire(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_generation = sse_decode_u_64(deserializer);
        var var_seg = sse_decode_u_32(deserializer);
        var var_detail = sse_decode_list_wire_column(deserializer);
        var var_overview = sse_decode_list_wire_column(deserializer);
        return AnalysisEventWire_Segment(
          generation: var_generation,
          seg: var_seg,
          detail: var_detail,
          overview: var_overview,
        );
      case 1:
        var var_generation = sse_decode_u_64(deserializer);
        var var_bpm = sse_decode_f_64(deserializer);
        var var_keyName = sse_decode_String(deserializer);
        var var_keyCamelot = sse_decode_String(deserializer);
        var var_offsetSecs = sse_decode_f_64(deserializer);
        var var_beatsSecs = sse_decode_list_prim_f_64_strict(deserializer);
        var var_downbeatsSecs = sse_decode_list_prim_f_64_strict(deserializer);
        var var_confidence = sse_decode_f_32(deserializer);
        var var_tempoSegments = sse_decode_list_record_f_64_f_64_f_32(
          deserializer,
        );
        return AnalysisEventWire_TrackAnalysis(
          generation: var_generation,
          bpm: var_bpm,
          keyName: var_keyName,
          keyCamelot: var_keyCamelot,
          offsetSecs: var_offsetSecs,
          beatsSecs: var_beatsSecs,
          downbeatsSecs: var_downbeatsSecs,
          confidence: var_confidence,
          tempoSegments: var_tempoSegments,
        );
      case 2:
        var var_generation = sse_decode_u_64(deserializer);
        var var_detail = sse_decode_list_wire_column(deserializer);
        var var_overview = sse_decode_list_wire_column(deserializer);
        var var_framesPerCol = sse_decode_u_32(deserializer);
        var var_sampleRate = sse_decode_u_32(deserializer);
        var var_durationFrames = sse_decode_u_64(deserializer);
        return AnalysisEventWire_Done(
          generation: var_generation,
          detail: var_detail,
          overview: var_overview,
          framesPerCol: var_framesPerCol,
          sampleRate: var_sampleRate,
          durationFrames: var_durationFrames,
        );
      case 3:
        var var_generation = sse_decode_u_64(deserializer);
        var var_msg = sse_decode_String(deserializer);
        return AnalysisEventWire_Failed(
          generation: var_generation,
          msg: var_msg,
        );
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DeckSnapshotWire sse_decode_deck_snapshot_wire(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_playhead = sse_decode_f_64(deserializer);
    var var_duration = sse_decode_f_64(deserializer);
    var var_loaded = sse_decode_f_64(deserializer);
    var var_playing = sse_decode_f_64(deserializer);
    var var_vu = sse_decode_f_64(deserializer);
    var var_rate = sse_decode_f_64(deserializer);
    var var_volume = sse_decode_f_64(deserializer);
    var var_bpm = sse_decode_f_64(deserializer);
    var var_gridBpm = sse_decode_f_64(deserializer);
    var var_keylock = sse_decode_f_64(deserializer);
    var var_sync_ = sse_decode_f_64(deserializer);
    var var_loopActive = sse_decode_f_64(deserializer);
    var var_loopIn = sse_decode_f_64(deserializer);
    var var_loopOut = sse_decode_f_64(deserializer);
    var var_eqLow = sse_decode_f_64(deserializer);
    var var_eqMid = sse_decode_f_64(deserializer);
    var var_eqHigh = sse_decode_f_64(deserializer);
    var var_cacheFilled = sse_decode_f_64(deserializer);
    return DeckSnapshotWire(
      playhead: var_playhead,
      duration: var_duration,
      loaded: var_loaded,
      playing: var_playing,
      vu: var_vu,
      rate: var_rate,
      volume: var_volume,
      bpm: var_bpm,
      gridBpm: var_gridBpm,
      keylock: var_keylock,
      sync_: var_sync_,
      loopActive: var_loopActive,
      loopIn: var_loopIn,
      loopOut: var_loopOut,
      eqLow: var_eqLow,
      eqMid: var_eqMid,
      eqHigh: var_eqHigh,
      cacheFilled: var_cacheFilled,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FxEffectWire sse_decode_fx_effect_wire(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_32(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_params = sse_decode_list_fx_param_wire(deserializer);
    return FxEffectWire(
      id: var_id,
      name: var_name,
      label: var_label,
      params: var_params,
    );
  }

  @protected
  FxParamWire sse_decode_fx_param_wire(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_unit = sse_decode_String(deserializer);
    var var_kindStepped = sse_decode_bool(deserializer);
    var var_kindMin = sse_decode_f_64(deserializer);
    var var_kindMax = sse_decode_f_64(deserializer);
    var var_kindStep = sse_decode_f_64(deserializer);
    var var_defaultValue = sse_decode_f_64(deserializer);
    return FxParamWire(
      name: var_name,
      label: var_label,
      unit: var_unit,
      kindStepped: var_kindStepped,
      kindMin: var_kindMin,
      kindMax: var_kindMax,
      kindStep: var_kindStep,
      defaultValue: var_defaultValue,
    );
  }

  @protected
  List<FxEffectWire> sse_decode_list_fx_effect_wire(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FxEffectWire>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_fx_effect_wire(deserializer));
    }
    return ans_;
  }

  @protected
  List<FxParamWire> sse_decode_list_fx_param_wire(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FxParamWire>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_fx_param_wire(deserializer));
    }
    return ans_;
  }

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat64List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(double, double, double)> sse_decode_list_record_f_64_f_64_f_32(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(double, double, double)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_f_64_f_64_f_32(deserializer));
    }
    return ans_;
  }

  @protected
  List<WireColumn> sse_decode_list_wire_column(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <WireColumn>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_wire_column(deserializer));
    }
    return ans_;
  }

  @protected
  MasterSnapshotWire sse_decode_master_snapshot_wire(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_volume = sse_decode_f_64(deserializer);
    var var_vu = sse_decode_f_64(deserializer);
    return MasterSnapshotWire(volume: var_volume, vu: var_vu);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (double, double, double) sse_decode_record_f_64_f_64_f_32(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_f_64(deserializer);
    var var_field1 = sse_decode_f_64(deserializer);
    var var_field2 = sse_decode_f_32(deserializer);
    return (var_field0, var_field1, var_field2);
  }

  @protected
  TrackMetadataWire sse_decode_track_metadata_wire(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_opt_String(deserializer);
    var var_artist = sse_decode_opt_String(deserializer);
    var var_cover = sse_decode_list_prim_u_8_strict(deserializer);
    var var_coverMime = sse_decode_String(deserializer);
    return TrackMetadataWire(
      title: var_title,
      artist: var_artist,
      cover: var_cover,
      coverMime: var_coverMime,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WireColumn sse_decode_wire_column(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_lowP = sse_decode_u_8(deserializer);
    var var_lowN = sse_decode_u_8(deserializer);
    var var_midP = sse_decode_u_8(deserializer);
    var var_midN = sse_decode_u_8(deserializer);
    var var_highP = sse_decode_u_8(deserializer);
    var var_highN = sse_decode_u_8(deserializer);
    var var_allP = sse_decode_u_8(deserializer);
    var var_allN = sse_decode_u_8(deserializer);
    return WireColumn(
      lowP: var_lowP,
      lowN: var_lowN,
      midP: var_midP,
      midN: var_midN,
      highP: var_highP,
      highN: var_highN,
      allP: var_allP,
      allN: var_allN,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_analysis_event_wire_Sse(
    RustStreamSink<AnalysisEventWire> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_analysis_event_wire,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_all_snapshot_wire(
    AllSnapshotWire self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_deck_snapshot_wire(self.deck0, serializer);
    sse_encode_deck_snapshot_wire(self.deck1, serializer);
    sse_encode_master_snapshot_wire(self.master, serializer);
  }

  @protected
  void sse_encode_analysis_event_wire(
    AnalysisEventWire self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case AnalysisEventWire_Segment(
        generation: final generation,
        seg: final seg,
        detail: final detail,
        overview: final overview,
      ):
        sse_encode_i_32(0, serializer);
        sse_encode_u_64(generation, serializer);
        sse_encode_u_32(seg, serializer);
        sse_encode_list_wire_column(detail, serializer);
        sse_encode_list_wire_column(overview, serializer);
      case AnalysisEventWire_TrackAnalysis(
        generation: final generation,
        bpm: final bpm,
        keyName: final keyName,
        keyCamelot: final keyCamelot,
        offsetSecs: final offsetSecs,
        beatsSecs: final beatsSecs,
        downbeatsSecs: final downbeatsSecs,
        confidence: final confidence,
        tempoSegments: final tempoSegments,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_u_64(generation, serializer);
        sse_encode_f_64(bpm, serializer);
        sse_encode_String(keyName, serializer);
        sse_encode_String(keyCamelot, serializer);
        sse_encode_f_64(offsetSecs, serializer);
        sse_encode_list_prim_f_64_strict(beatsSecs, serializer);
        sse_encode_list_prim_f_64_strict(downbeatsSecs, serializer);
        sse_encode_f_32(confidence, serializer);
        sse_encode_list_record_f_64_f_64_f_32(tempoSegments, serializer);
      case AnalysisEventWire_Done(
        generation: final generation,
        detail: final detail,
        overview: final overview,
        framesPerCol: final framesPerCol,
        sampleRate: final sampleRate,
        durationFrames: final durationFrames,
      ):
        sse_encode_i_32(2, serializer);
        sse_encode_u_64(generation, serializer);
        sse_encode_list_wire_column(detail, serializer);
        sse_encode_list_wire_column(overview, serializer);
        sse_encode_u_32(framesPerCol, serializer);
        sse_encode_u_32(sampleRate, serializer);
        sse_encode_u_64(durationFrames, serializer);
      case AnalysisEventWire_Failed(
        generation: final generation,
        msg: final msg,
      ):
        sse_encode_i_32(3, serializer);
        sse_encode_u_64(generation, serializer);
        sse_encode_String(msg, serializer);
    }
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_deck_snapshot_wire(
    DeckSnapshotWire self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.playhead, serializer);
    sse_encode_f_64(self.duration, serializer);
    sse_encode_f_64(self.loaded, serializer);
    sse_encode_f_64(self.playing, serializer);
    sse_encode_f_64(self.vu, serializer);
    sse_encode_f_64(self.rate, serializer);
    sse_encode_f_64(self.volume, serializer);
    sse_encode_f_64(self.bpm, serializer);
    sse_encode_f_64(self.gridBpm, serializer);
    sse_encode_f_64(self.keylock, serializer);
    sse_encode_f_64(self.sync_, serializer);
    sse_encode_f_64(self.loopActive, serializer);
    sse_encode_f_64(self.loopIn, serializer);
    sse_encode_f_64(self.loopOut, serializer);
    sse_encode_f_64(self.eqLow, serializer);
    sse_encode_f_64(self.eqMid, serializer);
    sse_encode_f_64(self.eqHigh, serializer);
    sse_encode_f_64(self.cacheFilled, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_fx_effect_wire(FxEffectWire self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_list_fx_param_wire(self.params, serializer);
  }

  @protected
  void sse_encode_fx_param_wire(FxParamWire self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.unit, serializer);
    sse_encode_bool(self.kindStepped, serializer);
    sse_encode_f_64(self.kindMin, serializer);
    sse_encode_f_64(self.kindMax, serializer);
    sse_encode_f_64(self.kindStep, serializer);
    sse_encode_f_64(self.defaultValue, serializer);
  }

  @protected
  void sse_encode_list_fx_effect_wire(
    List<FxEffectWire> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_fx_effect_wire(item, serializer);
    }
  }

  @protected
  void sse_encode_list_fx_param_wire(
    List<FxParamWire> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_fx_param_wire(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_64_strict(
    Float64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_f_64_f_64_f_32(
    List<(double, double, double)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_f_64_f_64_f_32(item, serializer);
    }
  }

  @protected
  void sse_encode_list_wire_column(
    List<WireColumn> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_wire_column(item, serializer);
    }
  }

  @protected
  void sse_encode_master_snapshot_wire(
    MasterSnapshotWire self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.volume, serializer);
    sse_encode_f_64(self.vu, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_record_f_64_f_64_f_32(
    (double, double, double) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.$1, serializer);
    sse_encode_f_64(self.$2, serializer);
    sse_encode_f_32(self.$3, serializer);
  }

  @protected
  void sse_encode_track_metadata_wire(
    TrackMetadataWire self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.title, serializer);
    sse_encode_opt_String(self.artist, serializer);
    sse_encode_list_prim_u_8_strict(self.cover, serializer);
    sse_encode_String(self.coverMime, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_wire_column(WireColumn self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.lowP, serializer);
    sse_encode_u_8(self.lowN, serializer);
    sse_encode_u_8(self.midP, serializer);
    sse_encode_u_8(self.midN, serializer);
    sse_encode_u_8(self.highP, serializer);
    sse_encode_u_8(self.highN, serializer);
    sse_encode_u_8(self.allP, serializer);
    sse_encode_u_8(self.allN, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
